# Generated by Django 5.2.4 on 2025-07-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('---', 'Select Department'), ('CSE', 'Computer Science'), ('EEE', 'Electrical and Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('BBA', 'Bachelor of Business Administration'), ('BA', 'Bachelor of Arts'), ('BCOM', 'Bachelor of Commerce'), ('Other', 'Other')], default='---', max_length=500)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
